---
# This role installs HAProxy and configures it.

- name: Download and install haproxy and socat
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - haproxy
  - socat

- name: Enable haproxy service without changing its state
  service:
    name: haproxy
    enabled: true

- name: Configure firewall for access to website
  firewalld:
    permanent: yes
    service: http
    state: enabled
    immediate: yes
  tags: fw

- name: Configure firewall for access to stats page
  firewalld:
    permanent: yes
    port: 8080/tcp
    state: enabled
    immediate: yes
  tags: fw

- name: Configure the haproxy cnf file with hosts
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
