---
# This role installs HAProxy and configures it.

- name: Download and install haproxy
  yum:
    name: "haproxy"
    state: present

- name: Enable haproxy service without changing its state
  service:
    name: haproxy
    enabled: true

# here a notifier is used. When the file actually changes, the handler called "restart haproxy" will be executed at the
# end of this playbook.
- name: Configure the haproxy cnf file with hosts
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Configure firewall for access to website
  firewalld:
    permanent: yes
    service: http
    state: enabled
    immediate: yes

- name: Configure firewall for access to stats page
  firewalld:
    permanent: yes
    port: 8080/tcp
    state: enabled
    immediate: yes
