---
- name: Create website on webserver
  hosts: role_webserver:&linux
  become: yes
  vars_files:
    files/database_credentials.yml
  vars:
    dbserver: "{{ groups['role_dbserver'][0] }}"

  tasks:
  - name: Install git
    yum:
      name: "git"
      state: present

  - name: check out website from git
    git:
      repo: https://github.com/fvzwieten/simple_db_app.git
      dest: /var/www/html/
      force: yes

  - name: Create website configuration file
    template:
      src: files/config.php.j2
      dest: /var/www/html/config.php
      
  - name: Report IP endpoint
    debug:
      msg: "SSH & Website at {{ public_ip }}. Web Console at :9090"
