# Configure and deploy the load balancer(s).
#- hosts: role_webserver
#  name: Gather facts from webservers
#  vars_files:
#  - winrm_vars.yml
#  tasks: [ ]
---
- name: Deploy ha proxy load balancer
  hosts: role_lbserver
  become: yes
  
  roles:
  - haproxy
  
  tasks:
  - name: Report IP endpoint
    debug:
      msg: "Load Balanced Website on-line at {{ public_ip }}"
      msg: "Loadbalancer admin on-line at {{ public_ip }}:8080"
