---
- name: all
  hosts: all
  gather_facts: no
  tasks:
  # show username and password from machine credential
  - name: Show machine credentials
    debug:
      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"
  
- name: localhost
  hosts: localhost
  gather_facts: no

  tasks:
  # show username and password from machine credential
  - name: Show machine credentials
    debug:
      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"
      
#  - name: ping it
#    ping:
