---
- name: Install website on webserver
  hosts: role_webserver
  become: yes
  
  tasks:
  - name: check out website from git
    git:
      repo: https://github.com/fvzwieten/simple_db_app.git
      dest: /var/www/html/
