---
- name: create database on database server
  hosts: dbservers:&linux
  become: yes
  vars_files:
    database_credentials.yml

  tasks:
  - name: Remove database is it already exists
    mysql_db:
      name: "{{ dbname }}"
      state: absent
  - name: Create Database
    mysql_db:
      name: "{{ dbname }}"
      state: present
  - name: Copy database schema file to DB server
    template:
      src: schema.sql.j2
      dest: /tmp/schema.sql
  - name: Import schema file into database
    mysql_db:
      name: my_db
      state: import
      target: /tmp/schema.sql
  - name: Create DB User
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      priv: "*.*:ALL"
      host: "%"
      state: present      
