---
- name: This playbook will install MariaDB (MySQL) 
  hosts: role_dbserver:&linux
  become: yes
  
  roles:
  - cockpit

  tasks:
  - name: Install Mariadb Server
    yum:
      name: "{{ item }}"
      state: present
    loop:
     - mariadb-server
     - MySQL-python

  - name: Start MariaDB Service
    service:
      name: mariadb
      state: started
      enabled: true
      
  - name: Configure host based firewall for access
    firewalld:
      permanent: yes
      service: mysql
      state: enabled
      immediate: yes
      
  - name: Report end-points
    debug:
      msg: "SSH at {{ public_ip }}. Web console at :9090"
