# Configure and deploy the load balancer(s).
#- hosts: role_webserver
#  name: Gather facts from webservers
#  vars_files:
#  - winrm_vars.yml
#  tasks: [ ]
---
- name: Deploy ha proxy load balancer
  hosts: role_lbserver

  roles:
  - haproxy
