---
- name: create database on database server
  become: yes
  vars_files:
    https://raw.githubusercontent.com/fvzwieten/simple_db_app/master/database_credentials.yml'

  hosts: role_dbserver
  tasks:
  - name: Remove database is it already exists
    mysql_db:
      name: "{{ dbname }}"
      state: absent
  - name: Create Database
    mysql_db:
      name: "{{ dbname }}"
      state: present
  - name: Copy database schema file to DB server
    template:
      src: schema.sql.j2
      dest: /tmp/schema.sql
  - name: Import schema file into database
    mysql_db:
      name: my_db
      state: import
      target: /tmp/schema.sql
  - name: Create DB User
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      priv: "*.*:ALL"
      host: "%"
      state: present      
