---
- name: get machine credentials
  hosts: blabla
  gather_facts: no
  tasks:
  - name: cache machine credentials
    set_stats:
      data:
        user: "{{ansible_username}}"
        pwd: "{{ansible_password}}"
      
- name: use machine credentials
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  # show username and password from machine credential
  - name: show machine credentials
    debug:
      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"

  - name: show cached machine credentials
    debug:
      msg: "Machine username = {{ user }} password = {{ pwd }}"

