---
- name: ping the servers
  hosts: all

  tasks:
  # show username and password from machine credential
  - name: Show machine credentials
    debug:
      msg: "Machine username = {{ ansible_user }}"
      
  - name: ping it
    ping:
