---
# this playbook joins a RHEL server to a Windows AD domain
# It depend on external (extra) vars to supply the domain name and the other
# variables

- name: join a server to a Domain
  become: yes
  hosts: linux
  vars_files:
    files/join_domain_vars
  vars:
    dcserver: "{{ groups['role_dcserver'][0] }}"
    fqdn: "{{ ansible_hostname }}.{{ domain }}"

  tasks:
  - name: set fqdn
    hostname:
      name: "{{ fqdn }}"
  - name: set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam
      hwclock: UTC

  - name: add fqdn entry to hosts file
    lineinfile:
      path: /etc/hosts
      regexp: "{{ fqdn }}"
      line: "127.0.0.1 {{ fqdn }} {{ ansible_hostname }}"

  - name: Install AD related software
    yum:
      name: ['krb5-workstation', 'samba-common-tools', 'sssd-ad', 'oddjob-mkhomedir']
      state: installed

#  - include_role:
#      name: geerlingguy.ntp
#    tags:
#      - time

  - name: Disable dns server setting by NetworkManager (needed for Azure)
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none

  - name: Overrule DNS server settings (needed for Azure)
    template:
      src: files/resolv.conf.j2
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: configure Kerberos
    template:
      src: files/krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644

  - name: configure Samba
    template:
      src: files/smb.conf.j2
      dest: /etc/samba/smb.conf
      owner: root
      group: root
      mode: 0644

  - name: get admin credentials
    shell: |
      echo {{ ad_password }} | kinit {{ ad_user }}

  - name: join machine to domain
    shell: |
      net ads join -k
    args:
      creates: /etc/krb5.keytab

  - name: remove admin credentials
    shell: |
      kdestroy

  - name: place pam and authconfig configuration files, fingerprint-auth-ac
    copy:
      src: files/fingerprint-auth-ac
      dest: /etc/pam.d/fingerprint-auth-ac
      owner: root
      group: root
      mode: 0644

  - name: place pam and authconfig configuration files, password-auth-ac
    copy:
      src: files/password-auth-ac
      dest: /etc/pam.d/password-auth-ac
      owner: root
      group: root
      mode: 0644

  - name: place pam and authconfig configuration files, smartcard-auth-ac
    copy:
      src: files/smartcard-auth-ac
      dest: /etc/pam.d/smartcard-auth-ac
      owner: root
      group: root
      mode: 0644

  - name: place pam and authconfig configuration files, system-auth-ac
    copy:
      src: files/system-auth-ac
      dest: /etc/pam.d/system-auth-ac
      owner: root
      group: root
      mode: 0644

  - name: place pam and authconfig configuration files, authconfig
    copy:
      src: files/authconfig
      dest: /etc/sysconfig/authconfig
      owner: root
      group: root
      mode: 0644

  - name: configure sssd
    template:
      src: files/sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600

  - name: start sssd
    service:
      name: sssd
      state: started
      enabled: yes

  - name: start oddjobd
    service:
      name: oddjobd
      state: started
      enabled: yes

  - name: place sudoers file for domain admins
    copy:
      src: files/domain_admins_sudoers
      dest: /etc/sudoers.d/domain_admins_sudoers
      owner: root
      group: root
      mode: 0400
