# Configure and deploy the load balancer(s).
---
- name: Deploy ha proxy load balancer
  hosts: role_lbserver
  become: yes
  
  roles:
  - cockpit
  - haproxy
  
  tasks:
  - name: Report IP endpoint
    debug:
      msg: "Load Balanced Website on-line at {{ public_ip }}. Loadbalancer at :8080, Web console at :9090"
