---
- name: Create website on webserver
  hosts: webservers:&linux
  become: yes
  vars_files:
    database_credentials.yml
  vars:
    dbserver: "{{ groups['dbservers'][0] }}"

  tasks:
  - name: Install git
    yum:
      name: "git"
      state: present

  - name: check out website from git
    git:
      repo: https://github.com/fvzwieten/simple_db_app.git
      dest: /var/www/html/
      force: yes

  - name: Create website configuration file
    template:
      src: config.php.j2
      dest: /var/www/html/config.php
