---
- name: all
  hosts: all
  gather_facts: no
  tasks:
  # show username and password from machine credential
  - name: Show machine credentials
    debug:
      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"

  - name: catch machine account
    set_fact:
      machine_user = "{{ ansible_user }}"
      machine_password = "{{ ansible_password }}"

- name: localhost
  hosts: localhost
  gather_facts: no

  tasks:
  # show username and password from machine credential
  - name: Show machine credentials
    debug:
      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"

  # show username and password from machine credential
  - name: Show catched machine credentials
    debug:
      msg: "Machine username = {{ machine_user }} password = {{ machine_password }}"
      
#  - name: ping it
#    ping:
