---
- name: get machine credentials
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add dummy host
    add_host:
      name: "dummy"
      foo: "42"

  - name: show machine credentials
    debug:
#      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"
       var: hostvars["dummy"]

  #- name: cache machine credentials
  #  set_fact:
  #    user: "{{ansible_username}}"
  #    pwd: "{{ansible_password}}"

- name: use machine credentials
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  # show username and password from machine credential
  - name: show machine credentials
    debug:
#      msg: "Machine username = {{ ansible_user }} password = {{ ansible_password }}"
       var: hostvars["dummy"]

#  - name: show cached machine credentials
#    debug:
#      msg: "Machine username = {{ user }} password = {{ pwd }}"

