---
# This playbook will install MySQL (MariaDB) and create db user and give permissions.
- name: linux_install_db
  hosts: role_dbserver

  tasks:
  - name: Install Mysql package
    yum:
      name: "{{ item }}"
      state: present
    with_items:
     - mariadb-server
     - MySQL-python

  - name: Start Mysql Service
    service:
      name: mariadb
      state: started
      enabled: true

  - name: Create Application Database
    mysql_db:
      name: "{{ dbname }}"
      state: present

  - name: Create Application DB User
    mysql_user:
      name: "{{ dbuser }}"
      password: "{{ dbpassword }}"
      priv: "*.*:ALL"
      host: "%"
      state: present
