---
# This playbook will install Apache Web Server with php and mysql support
- name: linux_deploy_apache
  hosts: role_webserver:&linux
  become: yes
  
  roles:
  - role: cockpit

  tasks:
  - name: Install apache and php
    yum:
      name: "{{ item }}"
      state: present
    loop:
     - httpd
     - php
     - php-mysql
     - libsemanage-python
     - git

  - name: Start Apache Webserver
    service:
      name: httpd
      state: restarted

  - name: Configure SELinux to allow httpd to connect to remote database
    seboolean:
      name: httpd_can_network_connect_db
      state: true
      persistent: yes

  - name: Configure host based firewall for access
    firewalld:
      permanent: yes
      service: http
      state: enabled
      immediate: yes
