---
# This playbook will install MySQL (MariaDB) and create db user and give permissions.
- name: linux_install_db
  hosts: role_dbserver
  become: yes

  tasks:
  - name: Install Mysql package
    yum:
      name: "{{ item }}"
      state: present
    loop:
     - mariadb-server
     - MySQL-python

  - name: Start Mysql Service
    service:
      name: mariadb
      state: started
      enabled: true
      
  - name: Configure host based firewall for access
    firewalld:
      permanent: yes
      service: mysql
      state: enabled
      immediate: yes
